### ISSUE TITLE
Remove strict errors on styling preferences

### ISSUE THREAD

**Issue by JeffreyArts** [wearereasonablepeople/eslint-config-warp#2]
I find it f*@&$#* frustrating that I can not commit changes in file A since someone else messed up a spacing after a semicolon in file B. So pleaasssssssssse remove the error on styling preferences. I even had an occasion where I could not commit (so I removed the githook) because for a specific 3rd party API it was expecting a key in kebab-case instead of CamelCase, and therefor I wasn't able to commit anything.

Ofcourse, removing githooks are a solution. But shouldn't these be errors in the first place. It should just be warnings.

**Comment by Avaq** [comment]
This was discussed internally. I'll post the results for reference:

>> I can not commit changes in file
>
> You can always use `git commit --no-verify` to bypass commit hooks

>> someone else messed up a spacing
>
> Use `git blame` and then teach this person how to code

>> a specific 3rd party API it was expecting a key in kebab-case instead of CamelCase
>
> Use `//eslint-disable-line`

>> removing githooks are a solution
>
>It's not a solution, it's moving the problem onto another developers plate

>> It should just be warnings
>
> Warnings are there to be ignored, the more warnings you get, the less likely you are to fix them. If you plan to ignore these things, it's better yet to remove the rules altogether by overriding them in your project `.eslintrc`, so that *real* warnings will still be taken seriously.

>> All sounds like answers to a problem which shouldn’t exist in the first place. How does it make anyone a better coder that he places a space after a function clarification. It makes him a cleaner developer perhaps. But how are these lints contributing in our prototypes? For now it is only slowing me down. I am resolving issues over here, someone else created. And there is no way I can “teach” this person about this by punishing to resolve these issues himself. Since that would slow me down even more.
>>
>> It only makes me more angry about this linting proces and I start disliking my colleagues who caused me this slowing down of my development proces. So ofcourse, yes I can bypass the hooks. But what is the purpose of writing these lints if that is the “suggested solution"
>
> You should never merge any commits into master (or any shared branch) that contain linting errors. The only time you use `--no-verfiy` is when you are creating a WIP commit for backup purposes. The person who caused these errors in the first place should also adhere to these rules. (edited)
> If you don't care about particular rules within your project, feel free to override them in `.eslintrc`.

>> Please note that I am not against linting at all, only against the styling errors. An error like this `'rows' is defined but never used` is really usefull
>
> The styling errors are there to preserve consistency. Consistency makes for cleaner `git diff`s. Cleaner `git diff`s makes for faster code reviewing. The rules we are using for styling should be a pay-off between time saved through messy code, and time saved though fast code-reviews.
>
> Simple stuff like spaces in function declarations can be inserted by eslint automatically by running `eslint --fix` (or in my skeleton; `npm run lint:fix`)
