### ISSUE TITLE
Add rules and globals for jest testing

### ISSUE THREAD

**Issue by paolobueno** [wearereasonablepeople/eslint-config-warp#6]
# Introduction
Globals and specific rules for `jest` are not catered for in these configs.

# Proposal
- Add a new `warp/jest` config that includes:
  - [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest) optional/peer dependency?
  - recommended set of rules from it
- maybe add instructions to the readme so it's used from an override only for `*.{test,spec}.js` files

**Comment by Avaq** [comment]
Won't implement. Feel free to reopen if interest returns.
